### ISSUE TITLE
LiProd environment setup

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#1]
When clicking on the LiPROD 1.0.0-alpha shortcut for the first time I am getting these credential prompts.

I've tried this on multiple machines and I keep on getting the same prompt.

![image](https://user-images.githubusercontent.com/35336539/83424909-156ff900-a3fb-11ea-963d-743b7c93f6c9.png)

Once I enter credentials I get the following prompt of cannot find path.

![image](https://user-images.githubusercontent.com/35336539/83425340-8fa07d80-a3fb-11ea-9312-82d96dec0660.png)

**Comment by forkozi** [comment]
this was related to LiProd assuming the wrong Anaconda installation directory; modified the "installation" bat file to automatically detect the correct location
