### ISSUE TITLE
ran but then liProd found an error...

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#10]
Hi Nick,

I put the server string like Jamie suggested to run Liprod:
![image](https://user-images.githubusercontent.com/44785008/85186593-efa27b00-b267-11ea-929c-8f90fa1122ec.png)

Looks like it started... but not sure what happened...
will email you the other screen grabs... 
thx,
g

**Comment by forkozi** [comment]
hey hey.  did you specify the OCS staging directory in the LiPROD settings?

**Comment by forkozi** [comment]
oh wait...sorry, that's something different.  I meant "tracker directory"
in LiPROD settings.
