### ISSUE TITLE
Project Title Customization for deliverable tiled products

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#11]
Looking for an enhancement to have more control over project prefix for deliverable products.  Currently using the root folder name of user selected Project folder.  Would be nice to have a user entered project name which will be the project prefix for the deliverable.   Not all project folder names are the final project names.

**Comment by forkozi** [comment]
It'll be easy to add an input for this...will be in v1.0.0-beta

**Comment by forkozi** [comment]
added to v1.0.0-beta
