### ISSUE TITLE
liprod-1.0.0-beta | paramiko module

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#12]
If user has a previous version of LiProd installed without the paraiko module installed then user will get a ModuleNotFoundEroor.

I just installed the paramiko module manually in my LiProd environment to work around this.

![image](https://user-images.githubusercontent.com/35336539/86025826-b18e1f80-b9fc-11ea-9253-586bf9eb2232.png)

**Comment by forkozi** [comment]
ah yes...i need to regenerate the environment file.  (paramiko was added for the NBS FTP functionality) i'll add that for v1.0.1-beta.  thanks.

**Comment by gimahori** [comment]
Ok just saw this too! thought I had delete something by accident when I deleted the anaconda_dir file.  Glad you are working on it!
