### ISSUE TITLE
LiPROD-1.0.1-beta | Solving for environment: failed 

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#13]
Running LiPROD-1.0.1-beta on a new rack machine and when it tries to download packages it gives me the following:

_PackagesNotFoundError: The following packages are not available from current channels:_

![image](https://user-images.githubusercontent.com/35336539/86621790-a8a8cb00-bf73-11ea-998c-b13344a6b1ac.png)

**Comment by forkozi** [comment]
@gimahori and @jkspring 
got it...it was a weird encoding thing.  somehow the file was encoded as "UCS-2 LE BOM."  Avoiding a deep deep rabbit's hole filled with subtle, yet important differences between flavors and incarnations of UTF and UCS...I simply saved the file as UTF-8 (in Notepad++, under the "Encoding" menu option), and all is well again with LiPROD.    I'll make sure the next environment file in the next release doesn't have this weird encoding.
