### ISSUE TITLE
what is this xml field?

### ISSUE THREAD

**Issue by forkozi** [noaa-rsd/LiProd#20]
https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/metadata_xml/metadata_template%20-%20Copy.xml#L194-L195

should this be autopopulated?

**Comment by stephen-a-white** [comment]
Probably a good idea to auto-populate from the LAS files.

**Comment by forkozi** [comment]
should it be the same date as the process date?

**Comment by stephen-a-white** [comment]
Sorry, was not paying attention to detail.  This is the date that the metadata was created.  We can just auto populate with the date when created if that makes things easy.  This should not come from the LAS files.

**Comment by forkozi** [comment]
doh...as it turns out, they were indeed already being autopopulated.  the fields just weren't marked "AUTO-POPULATED BY LIPROD" in the template xml.  They are now.
