### ISSUE TITLE
LAS 1.4 | Classification Scheme | Address

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#21]
How do we want to address las 1.4 classification scheme.  This is currently referencing las 1.2 classification scheme.

https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/metadata_xml/metadata_template%20-%20Copy.xml#L19

**Comment by jkspring** [comment]
Issue closed...addressed in json library.

**Comment by forkozi** [comment]
how about we change it to **<supplinf>AUTO-POPULATED BY LIPROD</supplinf>** ...and let the library take care of it?

**Comment by forkozi** [comment]
haha!...you closed it moments before i submitted that last comment
