### ISSUE TITLE
how to deal with LAS files with no TPU extra bytes (for surveys with TPU)?

### ISSUE THREAD

**Issue by forkozi** [noaa-rsd/LiProd#22]
For surveys that have TPU, what should LiPROD do with LAS files that don't have TPU for some reason (e.g., something went wrong with a particular file during cBLUE processing)?  Should LiPROD exclude it?

**Comment by stephen-a-white** [comment]
Probably should have a warning for the user to check and see why the LAS file does not have TPU, but maybe we should go ahead and exclude it initially.  The produced product might help the user diagnose where and why this file does not have TPU.

**Comment by jkspring** [comment]
Agree...a warning would be nice but ultimately this should also be caught in the QA/QC of the final deliverable.

**Comment by forkozi** [comment]
For now, LiPROD will output (to the console) a list of the las files that don't have (but should) total_thu and total_tvu extra bytes.  In the future, i'd like to add this to a better organized logging system.
