### ISSUE TITLE
Metedata Accuracy

### ISSUE THREAD

**Issue by stephen-a-white** [noaa-rsd/LiProd#23]
https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/metadata_xml/metadata_template%20-%20Copy.xml#L93

Maybe we should change to:

The data positions were obtained using post processed KGPS methods. Data used to test the lidar was collected with Static GPS Observations and compared against the published data.  The vertical accuracy of the data meets a bathymetric quality level vertical RMSE of QL2B specified in the National Coastal Mapping Strategy 1.0 Document (https://iocm.noaa.gov/iwg/IWG-OCM-Final-Coastal-Mapping-Strategy-2018-with-cover.pdf ).

**Comment by stephen-a-white** [comment]
Updated based on Nick's supplemental info.  This is probably where we should include information on how uncertainty was derived and is reported:

The data positions were obtained using post processed KGPS methods. Data used to test the lidar was collected with Static GPS Observations and compared against the published data. The vertical accuracy of the data meets a bathymetric quality level vertical RMSE of QL2B specified in the National Coastal Mapping Strategy 1.0 Document (https://iocm.noaa.gov/iwg/IWG-OCM-Final-Coastal-Mapping-Strategy-2018-with-cover.pdf ). The Geotiff has three bands: 1) Chart-Datum Heights (<CHART_DATUM>), 2) Total Horizontal Uncertainty (THU), and 3) Total Vertical Uncertainty (TVU). The THU band was generated by first using cBLUE (https://noaa-rsd.github.io/cBLUE.github.io/) to calculate per-point propagated horizontal uncertainties and then using PDAL to grid the cBLUE THU values at a 1-m resolution using mean resampling with a sampling radius of square_root(2). The TVU band was generated by combining in quadrature a TVU grid (generated using the same method used to generate the THU band) and the co-registered maximum cumulative uncertainty (MCU) model of the VDatum vertical-transformation model characterizing the separation between the ellipsoid and the specified chart datum. Please refer to https://vdatum.noaa.gov/docs/est_uncertainties.html for documentation on MCU.

**Comment by forkozi** [comment]
okie dokie, I updated it.   Should I revise other sections to avoid repetition of the explanation of the three bands, or is repetition fine?

**Comment by stephen-a-white** [comment]
We probably should decrease replication where we can.  It is not a big deal, but if we update it in the future, we have to remember to update in both locations, which I always seem to forget.

**Comment by forkozi** [comment]
how about this, to avoid duplication?...

what if we put the following in \<vertaccr\>...
>The data positions were obtained using post processed KGPS methods. Data used to test the lidar was collected with Static GPS Observations and compared against the published data. The vertical accuracy of the data meets a bathymetric quality level vertical RMSE of QL2B specified in the National Coastal Mapping Strategy 1.0 Document (https://iocm.noaa.gov/iwg/IWG-OCM-Final-Coastal-Mapping-Strategy-2018-with-cover.pdf ). 

...and put this in the \<procdesc\>...
>The Geotiff has three bands: 1) Chart-Datum Heights (<CHART_DATUM>), 2) Total Horizontal Uncertainty (THU), and 3) Total Vertical Uncertainty (TVU). The THU band was generated by first using cBLUE (https://noaa-rsd.github.io/cBLUE.github.io/) to calculate per-point propagated horizontal uncertainties and then using PDAL to grid the cBLUE THU values at a 1-m resolution using mean resampling with a sampling radius of square_root(2). The TVU band was generated by combining in quadrature a TVU grid (generated using the same method used to generate the THU band) and the co-registered maximum cumulative uncertainty (MCU) model of the VDatum vertical-transformation model characterizing the separation between the ellipsoid and the specified chart datum. Please refer to https://vdatum.noaa.gov/docs/est_uncertainties.html for documentation on MCU.

**Comment by stephen-a-white** [comment]
sounds good!

**Comment by forkozi** [comment]
done.
