### ISSUE TITLE
No VDatum in product1

### ISSUE THREAD

**Issue by stephen-a-white** [noaa-rsd/LiProd#25]
https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/support_files/library.json#L7

I think we can take the following VDatum reference out since it is not being used for this ellipsoidal product.

Remove: VDatum was used to process to the MLLW datum. Uncertainties in the vertical datum transformations equate to 8.96 centimeters.

**Comment by forkozi** [comment]
roger that.  done.
