### ISSUE TITLE
QTModeler?

### ISSUE THREAD

**Issue by stephen-a-white** [noaa-rsd/LiProd#27]
https://github.com/noaa-rsd/LiProd/blob/0f4209e08ca5637f6243966554b12097d7d5fbb1/support_files/library.json#L7

Since we are not using QT Modeler to create the DEM, we probably should specify the tool being utilized for the raster creation in all of the products (PDAL?)

**Comment by forkozi** [comment]
how about this?...

> Data were processed to an initial LAS format using the Riegl RiProcess software. The Applanix POSPac software was used for GPS and inertial processing, and GeoCue, Terrasolid, and LP360 software for data visualization, 3D editing, and export to final LAS \<LAS VERSION\> files. Data were processed relative to the NAD83 horizontal and vertical datum (i.e. GRS80 ellipsoid). PDAL was used to create the 1-m resolution DEM from the following classes:  ground (\<GROUND CLASS\>), bathymetric point (\<BATHY CLASS\>), submerged object (\<SUBMERGED CLASS\>), and International Hydrographic Organization (IHO) S-57 object (\<IHO CLASS\>). The values in the DEM were not rounded (no rounding rule was applied).


i took out references to Vdatum ('cause it's product 1, which is w.r.t. to the ellipsoid, not mllw).  I also moved <LAS_VERSION> to 
 an earlier sentence to simplify the sentence with the gridded classes a bit.  I also changed some of the other wording ever so slightly.

**Comment by gimahori** [comment]
I think that sounds good !

**Comment by stephen-a-white** [comment]
Sounds good!
