### ISSUE TITLE
LiProd-1.0.1-alpha | Does not recognize all TPU tiles

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#3]
Seems _LiProd-1.0.1-alpha_ does not always recognize all TPU tiles.

Please check with directory:
\\ngs-s-rsd\Lidar_Contract00\FL1608\lidar\CLASSIFIED_LIDAR_TPU_2.2.1_no_mcu

_LiProd-1.0.1-alpha_ sees only 10 tiles

Went back to _LiProd-1.0.0-alpha_ and ran
_Li-Prod-1.0.0_ sees 264 tiles

Total las tiles in directory is 616.

**Comment by forkozi** [comment]
silly me forgot to delete a temporary indexing that looked at only 10 files for troubleshooting purposes;  fixed
