### ISSUE TITLE
ftps path error

### ISSUE THREAD

**Issue by forkozi** [noaa-rsd/LiProd#32]
As @gimahori reported in an email earlier, there's something funky going on with the NBS and MCD submission paths when using the LiPROD exe.   For example, when "ftps:\OCSFTP.NCD.NOAA.GOV\NBS" is entered into the NBS Submission Dir field (in the LiPROD Configuration window), the following error pops up in the console window.

[WinError 123] The filename, directory name, or volume label syntax is incorrect: 'ftps:\\OCSFTP.NCD.NOAA.GOV\\NBS' nbs_ftp_url ftps:\OCSFTP.NCD.NOAA.GOV\NBS

@klangrjt, have you noticed any weird things with Path objects from pathlib when using a pyinstaller'd exe?

**Comment by klangrjt** [comment]
Nope, this would be a new "feature".
I'll test on my machine.  I probably didn't catch this cause I was testing on my dev machine and not using network paths.

**Comment by forkozi** [comment]
hey @klangrjt, how do you create the exe?  is it a single command you run at the command line?  I'm curious to try it myself and see if i get the same error.  maybe its something to do with the differences between our python/anaconda?

**Comment by klangrjt** [comment]
Activate your liprod env then run:

pyinstaller LiProd.spec

**Comment by forkozi** [comment]
gosh...couldn't you have made it more complicated or something?

**Comment by forkozi** [comment]
mmm...well, we have a mystery.  I ran your spiffy spec file on my system, and the resulting exe runs without the error.  bizarre.  I'll keep trouble shooting today...

**Comment by klangrjt** [comment]
Not sure if you saw my message earlier, but I had Jamie test out with the
ftp link and he gets the error as well.

**Comment by forkozi** [comment]
seeing inconsistent behavior with resolving ftps paths; refactored relevant code to avoid doing so

**Comment by forkozi** [comment]
addressed in v1.0.0-rc3
