### ISSUE TITLE
LiPROD crashed -

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#34]
using LiPROD 1.0.0-rc3 - I tried running FL1813 (previous FL1703) - entered my info and LiPROD crashed after it asked about making a new project tracking file.

**Comment by forkozi** [comment]
could you attach a copy of the config.json file?

if you are using the exe, it might be worth switching to the .bat file so
we can more easily troubleshoot what's happening.  once we find out, i can
fix the exe so it doesn't crash and close.

**Comment by gimahori** [comment]
I see a .tracker file but no .json file - will try the bat file

**Comment by gimahori** [comment]
is the .bat file only in the old version? I don' see it in 1.0.0-rc3?

**Comment by klangrjt** [comment]
It should be in the source code zip file.

**Comment by klangrjt** [comment]
One more suggestion for debugging, if you run LiPROD.exe from a cmd window
it will keep the console open after crashing and should show any error
messages.

Gretchen, can you post what your inputs are into the GUI for LAS Dir and
LiPROD Configuration.

**Comment by gimahori** [comment]
The console was gone (everything was gone actually) after the tracker file was created... all I was left with was a an explorer window.
Will call you about the .bat file in the source code. I don't see it in the 1.0.0-rc3

**Comment by forkozi** [comment]
the bat file is in the zip file (see image)

Also (i know this part is annoying), but don't forget to first delete the
anaconda_dir.txt file. (i keep forgetting to remove that from the release).

definitely please call if anything pops up
[image: image.png]

**Comment by gimahori** [comment]
Ok roger forgot about the anaconda_dir.txt file - deleted it from the 1.0.0 rc2.
Did you send an image? I can't see it  - will call you and/or rudy in a bit - maybe faster

**Comment by gimahori** [comment]
Ok tried the LiPROD.exe in the command prompt Rudy like we discussed on the phone. Here is the screenshot showing it failed.
![image](https://user-images.githubusercontent.com/44785008/89555568-34657f80-d7de-11ea-8a13-0010e07498e3.png)

Will try the other script for rc3 with the .bat file like you suggested - thanks for telling me to download the other script. I didn't know that one had the .bat file. 

For future releases - can we please label the files so they have exe and bat in the labels so I know which one has one or the other in them? Sorry it is probably intuitive to you but wasn't to me.  Thank you :)

**Comment by klangrjt** [comment]
Can you download the exe version again (
https://github.com/noaa-rsd/LiProd/releases/download/v1.0.0-rc3/LiPROD.zip),
extract and try running the exe.

**Comment by gimahori** [comment]
will do!

**Comment by gimahori** [comment]
Nick - I ran FL1813 with the .bat file after deleting the old environment as we discussed earlier. I came back in to see how things were going and I see files created in the ellipsoid and support files folder under NBS but not the Chart datum folder and nothing in the MCD folder (well there are folders there but nothing in them). It isn't running anymore - looks like it may have crashed because I don't see anything up anymore. I see it updated the .tracker file but there is no .json file. Do you want me to send you anything? Not sure what happened.
thx,
g

**Comment by forkozi** [comment]
hey g.  did you happen to screengrab the console with any messages?

**Comment by gimahori** [comment]
No it was working and when I logged back in it was gone :( Jamie is trying to run it on the same workstation...I am running Rudy'snew exe version on a different project. I'll check back in when Jamie is done.

**Comment by forkozi** [comment]
roger that.  when you get a chance, would you be able to send the
config.json and settings.json files from the root liprod directory?

**Comment by gimahori** [comment]
here you go! thanks for your help!!!

[files for Nick rc3bat version.zip](https://github.com/noaa-rsd/LiProd/files/5038372/files.for.Nick.rc3bat.version.zip)

FL1608 worked on Rudy's updated .exe so I will test the FL1813 again this evening

**Comment by gimahori** [comment]
Hi Rudy - I just checked the FL1813 redo with the new .exe and everything seems to be working but there are no MCD files. let's talk Friday.

**Comment by gimahori** [comment]
Hi Nick,

Jamie, Rudy and I met on google hangouts re. FL1813 - jamie doesn't have files in the MCD folder either. Looks like the chart datum files were generated tho. Do you know what the problem could be?
thx,

**Comment by forkozi** [comment]
i think i've got it.  The las files are 1.4, but it looks like they have 1.2 classification codes.   As an example, the unique classes present in 2018_591000e_2901000n_TPU.las are array([ 1,  7,  8, 26], dtype=uint8).   As a visual indicator...if you look at the Product 2 DEMs, they seem to every so nicely exclude everything that would be water!  

![image](https://user-images.githubusercontent.com/34494717/89680688-73b8cc80-d8c1-11ea-9443-8c47f0f2d5e0.png)

LiPROD currently assumes the following...

        self.classes = {
            '1.2': {
                '<GROUND CLASS>': 2,
                '<BATHY CLASS>': 26,
                '<SUBMERGED CLASS>': 29,
                '<IHO CLASS>': 30},
            '1.4': {
                '<GROUND CLASS>': 2,
                '<BATHY CLASS>': 40,
                '<SUBMERGED CLASS>': 43}
            }

Should I modify LiPROD to grid 1.4 bathy even when it contains 1.2 codes?   ...or make the data people use the right codes :)

**Comment by jkspring** [comment]
I think we should modify to grid 1.4 data with the las 1.2 classification.
There should just be a few legacy products for this and the rest should be
on the updated classification scheme.

-J

**Comment by forkozi** [comment]
How would we handle the associated metadata file?  Any special verbiage for
the odd-ball legacy products?

**Comment by jkspring** [comment]
Let me take a look at what projects have this issue.  I think it is just a
handful and we may be able to edit the data manually.

**Comment by forkozi** [comment]
ok.  That would be good.  It's totally possible to modify the code to
account for whatever odd-ball cases, but it's so much easier and tidier not
to :)

**Comment by forkozi** [comment]
@stephen-a-white, could I verify with you how to treat the scenario where v1.4 las files contain v1.2 classification codes?  Would you want LiPROD to grid either 26 or 40 for bathy, or maybe have some sort of checkbox to override expected codes?

**Comment by stephen-a-white** [comment]
I think we could have a checkbox to override expected codes as you
suggested or we could make the files conform to what they should be.  It is
a little painful reprocessing all of these over again, but think that is
easier than creating code to work around these issues.  Because each issue
is just a little enough different, that each different situation would have
to be handled differently in code.  Think it is easier, just making the
files conform to what they should be.

Just my thoughts.

Thanks,
-Stephen

**Comment by gimahori** [comment]
Would the metadata then be exactly the same as las 1.2 ? or would you want to have something that would be in the middle?  I drafted something below for consideration.  Not sure whatelse may have changed for the las 1.4 format other than the classes.

  <supplinf>The lidar point data used to generate this product were processed to an initial LAS format using the Riegl RiProcess software. Applanix POSPac was used to process the trajectory, and GeoCue, Terrasolid, and LP360 were used for data visualization, 3D editing, and export to final LAS 1.4 formated files. An automated ground classification algorithm was used to determine bare-earth point classification. Please note: this survey is in a las 1.4 format but still has 1.2 las classification codes (e.g. bathy is class 26) </supplinf>

   <procdesc>This 1m-resolution Geotiff has three bands: 1) Ellipsoid heights (GRS80), 2) Total Horizontal Uncertainty (THU), and 3) Total Vertical Uncertainty (TVU).  Band 1 was generated by using PDAL to grid ASPRS LAS 1.2 classes 2 (ground), 26 (bathymetric point), and 29 (submerged object), using mean resampling with a sampling radius of square_root(2). Band 2 was generated in two steps.

**Comment by jkspring** [comment]
I'm thinking we only have a handful of projects that are las 1.4 with the
las 1.2 classification.  I can run Qchecker on the one's I suspect.

**Comment by forkozi** [comment]
Is this issue something we should sort out before releasing v1.0.0?  It sounds like there are a couple ideas about what to do...  :)

**Comment by stephen-a-white** [comment]
Nick,
I think we are good to go. If we find an issue with the classification on a
project, we can run a routine to get the classes mapped correctly.  I think
that is easier than creating numerous workarounds.  Just let me know if we
need to have a quick group discussion.
Thanks,
-Stephen

**Comment by forkozi** [comment]
Roger that.  I like that approach, too.
