### ISSUE TITLE
VA1802 crash

### ISSUE THREAD

**Issue by forkozi** [noaa-rsd/LiProd#35]
_(originally reported by user @gimahori  in email)_
Also, I was running VA1802 on another rack because I was testing to see if it would run all the way through.  Had some issues earlier with this project on previous releases.  Looks like it didn't finish and closed down the program on the rack I was working on.

**Comment by forkozi** [comment]
I'm guessing it's because the DEM extents for cell US4VA1FH do not intersect the VDatum MCU region coverage (see image below)...will investigate further.  (Cell US4VA1FH is the only cell that LiPROD didn't generate an MCU model for.)

![image](https://user-images.githubusercontent.com/34494717/89543490-02005600-d7cf-11ea-8f77-efb5f166e699.png)

**Comment by forkozi** [comment]
It looks like cell US4VA1FH successfully ran in previous version with different user (see tracker info below).  still investigating...

`2020-08-01 07:22:36,VA1802-TB-N,US4VA1FH,1,GENERATE,SUCCESS,1.0.0-rc2,Jamie.Kum,"['\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\nbs\\VA1802-TB-N\\ellipsoid\\VA1802-TB-N_US4VA1FH_ellipsoidal_dem.tif', '\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\nbs\\VA1802-TB-N\\ellipsoid\\VA1802-TB-N_US4VA1FH_ellipsoidal_metadata.xml', '\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\nbs\\VA1802-TB-N\\ellipsoid\\VA1802-TB-N_US4VA1FH_ellipsoidal_dem.tif', '\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\nbs\\VA1802-TB-N\\ellipsoid\\VA1802-TB-N_US4VA1FH_ellipsoidal_metadata.xml']"
`

**Comment by forkozi** [comment]
confirmed my suspicion...here's the error.

The issue is there's no MCU region geometry to rasterize.  I'll add an if/then to account for the case where there's no mcu coverage.
![image](https://user-images.githubusercontent.com/34494717/89653931-da27f580-d895-11ea-9fe9-d4edfc185e2b.png)

**Comment by gimahori** [comment]
Thanks Nick!
