### ISSUE TITLE
project_tracker folder

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#36]
Hi All,

I put a copy of our current project_tracker folder in the Archive folder (\iocm_deliverables\ocs\Archive) so we could start adding new projects using the new LiPROD 'production' or 'near production' version per discussions with Jamie.  Just in case someone is looking for files from previous versions.  If no one wants these files - please let me know and I'll delete it. Also, if this type of notice should be somewhere else on github or in an email to the group separately - jlmk. I realize its not a software issue.
thx,
g

**Comment by forkozi** [comment]
Hey hey.  It's not a big deal at all, but yeah, this sort of thing might be better as an email.  Ooooorrr, we could create a team page for LiPROD like we did for SatBathy.   That way, any discussion pertaining to LiPROD would live with the repo, versus individual's email.

**Comment by gimahori** [comment]
Ok - I'm good with either :)

**Comment by forkozi** [comment]
ok, i'll go ahead and create a Team LiPROD
