### ISSUE TITLE
LiPROD_V1.0.0 | Traceback_Error | Determining Project Spatial Reference

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#37]
I'm getting a traceback error when trying to initialize project FL1613-TB-N_BLK02. 

We did have issues with running this project through in the alpha version but was able to move forward by removing files with a size of 2k or smaller.  All "small" files were moved out of the main directory when trying to run with release v1.0.0 but LiPROD shuts down and gives the following error when trying to determine the spatial reference.

_determining project spatial reference...
Traceback (most recent call last):
  File "LiPROD.py", line 481, in <module>
  File "LiPROD.py", line 329, in scan_project
  File "LiPROD.py", line 260, in set_crs_info
  File "site-packages\rasterio\crs.py", line 342, in from_string
rasterio.errors.CRSError: CRS is empty or invalid: ''
[20164] Failed to execute script LiPROD_

**LAS Files: \\ngs-s-rsd\Geocue01\iocm_deliverables\lidar\FL1613-TB-N\02\las_tpu_v2.1.1_no_mcu**

![image](https://user-images.githubusercontent.com/35336539/90457924-bfcdf300-e0b1-11ea-9f74-d8dc41093a1f.png)

**Comment by forkozi** [comment]
Well, if all of the files are like //ngs-s-rsd/Geocue01/iocm_deliverables/lidar/FL1613-TB-N/02/las_tpu_v2.1.1_no_mcu/2016_534000e_2749000n_TPU.las, it looks like there's no crs/srs metadata in the las header (see below).   (A Q-Checker check shows all the las files have the same "None " value for hdatum.)   Would you expect something like that with this project?

{
  "file_size": 10470905,
  "filename": "\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\lidar\\FL1613-TB-N\\02\\las_tpu_v2.1.1_no_mcu\\2016_534000e_2749000n_TPU.las",
  "metadata": {
    "comp_spatialreference": "",
    "compressed": false,
    "count": 290840,
    "creation_doy": 124,
    "creation_year": 2017,
    "dataformat_id": 1,
    "dataoffset": 665,
    "filesource_id": 0,
    "global_encoding": 1,
    "global_encoding_base64": "AQA=",
    "header_size": 227,
    "major_version": 1,
    "maxx": 534499.98,
    "maxy": 2748991.46,
    "maxz": 27.61,
    "minor_version": 2,
    "minx": 534264.53,
    "miny": 2748524.92,
    "minz": -455.9,
    "offset_x": 0,
    "offset_y": 0,
    "offset_z": 0,
    "point_length": 36,
    "project_id": "00000000-0000-0000-0000-000000000000",
    "scale_x": 0.01,
    "scale_y": 0.01,
    "scale_z": 0.01,
    "software_id": "TerraScan",
    "spatialreference": "",
    "srs": {
      "compoundwkt": "",
      "horizontal": "",
      "isgeocentric": false,
      "isgeographic": false,
      "prettycompoundwkt": "",
      "prettywkt": "",
      "proj4": "",
      "units": {
        "horizontal": "unknown",
        "vertical": ""
      },
      "vertical": "",
      "wkt": ""
    },
    "system_id": "",
    "vlr_0": {
      "data": "AAAJAHRvdGFsX3RodQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHRvdGFsX3RodQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAHRvdGFsX3R2dQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHRvdGFsX3R2dQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "description": "",
      "record_id": 4,
      "user_id": "LASF_Spec"
    }
  },
  "now": "2020-08-17T21:22:10-0400",
  "pdal_version": "2.1.0 (git-version: Release)",
  "reader": "readers.las"
}

**Comment by forkozi** [comment]
I should clarify that last statement...there's spatial reference metadata...at least as read by PDAL, which has been very robust with reading spatial reference metadata from 1.2 and 1.4 las files.

**Comment by jkspring** [comment]
Yep..that would do it.

User error.  Closing this one out.

**Comment by forkozi** [comment]
Roger that.  I'll add a little if/else thing to display a message in this scenario, instead of crashing out.
