### ISSUE TITLE
MCD_Product_3 | Gaps in DEM at tile borders

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#38]
Noticing gaps at our tile borders for the 5m_mllw_sb_ clip_ dem (MCD product 3)

**MD1702**

![image](https://user-images.githubusercontent.com/35336539/90828252-8c2ddb80-e2f2-11ea-8a4a-313341510b4a.png)

**FL1604**

![image](https://user-images.githubusercontent.com/35336539/90828270-92bc5300-e2f2-11ea-9ca0-a581da4e8f9b.png)

**Comment by forkozi** [comment]
To account for this edge effect, LiPROD now does product 3 processing using a buffered enc cell geometry.  This buffer (default value of 0.001 deg, or ~111 m) results in a area of overlap, which, in addition to eliminating the edge gap, provides near-edge context for cartographic compilation.

(@jkspring, @stephen-a-white, how does this sound?)

![image](https://user-images.githubusercontent.com/34494717/91313839-df38e000-e783-11ea-8462-a339d50e9809.png)

**Comment by forkozi** [comment]
Actually, to clarify...as it is, all products now use a buffered enc cell for processing.  Is the resulting area of overlap ok for NBS products, too (see image below), or should I change LiPROD to only buffer the enc cell for product 3 (i.e., MCD deliverables).
![image](https://user-images.githubusercontent.com/34494717/91317035-879c7380-e787-11ea-99fe-76158beee25a.png)

**Comment by stephen-a-white** [comment]
This might be something we need to check with Glen and Katrina on, if they
want overlap or not.

Gretchen, Can you check with Glen/Katrina on this?  Just let me know if you
would like me to.

Thanks,

**Comment by gimahori** [comment]
Yup I can check with them.  
thx,
g

**Comment by gimahori** [comment]
Glen said he doesn't think the overlap will cause problems with their process or how they implemented it but Katrina may have something to add. She returns back to work Monday.

**Comment by forkozi** [comment]
v1.1.0 now uses buffered ENC cells to address boundary-gap issue
