### ISSUE TITLE
LiPROD_Alpha 1.0.0 | vdatum_error

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#4]
Looks like I error'd out on a project (MA1602).  It did create the Products 1 deliverable and a portion of Products 2...I think.

Input las_tpu: 
//ngs-s-rsd/Geocue01/iocm_deliverables/lidar/MA1602-TB-N/las_tpu_v2.2.1_no_mcu

Project: //ngs-s-rsd/Lidar_Proc00/2015/BBay_880_Priority_01

I attached a text file with command line prompt text.
 
![image](https://user-images.githubusercontent.com/35336539/83768172-4fc3db00-a633-11ea-9ea8-21bcb6659f6b.png)
[LiPROD_Alpha_1.0.0_error_vdatum.txt](https://github.com/noaa-rsd/LiProd/files/4730605/LiPROD_Alpha_1.0.0_error_vdatum.txt)

**Comment by jkspring** [comment]
One more project where it error'd out during the vdatum process.

**Project: VA1703**
\\ngs-s-rsd\Lidar_Proc01\2017\VA1703-TB-N_880_Tabbs_Creek_p

**las_tpu_dir:**
\\ngs-s-rsd\Lidar_Proc01\2017\VA1703-TB-N_880_Tabbs_Creek_p\VA1703-TB-N_880_las\Green\09_VA1703-TB-N_880_Tabbs_Creek_g_gpsa_rf_ip_wsf_r_adj_tm_final_qc_FINAL_differentiateRERUN_tpu_final_v2.2.1_no_mcu


**Traceback:**

NOAA's Vertical Datum Transformation - v4.0.1

System.file.separator= \
System.path.separator= ;

cmdargs  :[Ljava.lang.String;@1b68ddbd
VConsole: dstHorzDatum--gov.noaa.vdatum.referencing.SupportedGeodeticDatum@21ae3502 dstCoorSysID--utm
FT: the transferred destination GeoInfo is: ohorz:NAD83_2011:utm:m:18 overt:MLLW:m:sounding:geoid12b region:3
Processed time (sec): 3.00000
merging partitioned separation models...
writing merged separation model...
creating mcu model...
generating coverage geometry feature...
Traceback (most recent call last):
  File "C:\LiProd-1.0.0-alpha\LiPROD.py", line 409, in <module>
    d2_product = p2.create_product(vals, dem_path)
  File "C:\LiProd-1.0.0-alpha\Products.py", line 218, in create_product
    self.create_coverage_shp(d2_tiff, coverage_shp)
  File "C:\LiProd-1.0.0-alpha\Products.py", line 61, in create_coverage_shp
    gdf.to_file(shp_path, driver='GeoJSON')
  File "C:\Users\Jamie.Kum\anaconda3\envs\liprod\lib\site-packages\geopandas\geodataframe.py", line 533, in to_file
    to_file(self, filename, driver, schema, index, **kwargs)
  File "C:\Users\Jamie.Kum\anaconda3\envs\liprod\lib\site-packages\geopandas\io\file.py", line 179, in to_file
    schema = infer_schema(df)
  File "C:\Users\Jamie.Kum\anaconda3\envs\liprod\lib\site-packages\geopandas\io\file.py", line 231, in infer_schema
    raise ValueError("Cannot write empty DataFrame to file.")
ValueError: Cannot write empty DataFrame to file.
(liprod) C:\LiProd-1.0.0-alpha>

**Comment by forkozi** [comment]
this has been fixed; the issue was there was no product coverage for the corresponding band-4 cell; add check to see if geometry exists
