### ISSUE TITLE
FL1813 crashed at initialization

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#40]
Hi All,

I put in the LAS Dir ( \\ngs-s-rsd\Lidar_Proc02\2018\FL1813-TB-N_880_FL_ICW_01_FY18_p\06_RIEGL_PROC\04_EXPORT\GR\06_FL1813_FL_ICW01_g_gpsa_rf_ip_r_tm_qc_final_m_r-n_gc_tpu_2.2.1_no_mcu\las_1.4_domain) for FL1813 in the LiPROD GUI and it crashed on initialization. The directory string was shorter than FL1606 so I figured I must have missed typed something and just decided to use the GUI button to drill down to the files.  When I got to  folder FL1813-TB-N_880_FL_ICW_01_FY18_p   --   I found there was no folder 06_RIEGL_PROC. Is this hidden? Or was it moved? If anyone knows that would be a great help since there is a gap in the MCD DEMs where they overlap ENC boundaries.

Thanks!
g

**Comment by forkozi** [comment]
Hey g.  Did you get to the bottom of this one, or do you still need info from folks?  I'm hoping to close out any lingering issues...

**Comment by gimahori** [comment]
Yes sorry - Jamie sent me the new directory string. Thx!
