### ISSUE TITLE
Project tracking file

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#42]
Hi,

Just a couple things we found when we were looking into FL1604:

1) Jamie - the project tracking file may be overwriting some of the surveys (Not FL1608, FL1802, FL1703) - can you please confirm? Or did you delete the older tracking files? I thought you did about half of the original surveys with V 1.0.0.  Just want to make sure we don't lose information and make sure this doesn't happen for the future. Don't worry about FL1611, FL1613 files but the ones we are planning on submitting: 
FL1604-TB-N
FL1605-TB-N
FL1606-TB-N
MD1702-TB-N
FL1607-TB-N
FL1608-TB-N
FL1703-TB-N
FL1808-TB-N
FL1802-TB-N
FL1813-TB-N 
VA1703- TB-N
VA1802-TB-N

2) Also, there are some weird old strings of a directory that I used to use (so I wouldn't copy over Jamie's test files) that are appearing in the project tracking file for FL1604 

e.g.  2020-08-18 06:26:00,FL1604-TB-N,project,1,GENERATE,SUCCESS,1.0.0,GRETCHEN.IMAHORI,"['\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\ocs\\Archive\\Testing\\FL1813-TB-Nv1\\NBS\\MA1602-TB-N\\MA1602-TB-N_Ellipsoid_metadata.xml', '\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\ocs\\Archive\\Testing\\FL1813-TB-Nv1\\NBS\\MA1602-TB-N\\MA1602-TB-N_overview.html', '\\\\ngs-s-rsd\\Geocue01\\iocm_deliverables\\nbs\\FL1604-TB-N\\FL1604-TB-N_Ellipsoid_metadata.xml']"

 -- we ran through the steps of deleting the old string and putting in the new one.  Do I need to clear out a cache? I started a new version with FL1604 so had to open it up and add the new string in (there wasn't an old one to delete). Not sure what is going on.

3)I'm going to save the FL1604 project tracking file and delete the one currently on there when I re-run the survey to see if its still doing this or if it stops.  I see this also in FL1605, FL1813 but not MD1702, FL1606, FL1607, FL1608, FL1802, FL1703, VA1703

g

**Comment by forkozi** [comment]
to clarify, what do you mean by " -- we ran through the steps of deleting
the old string and putting in the new one. "

**Comment by gimahori** [comment]
Oh yea that probably isn't clear - I meant in the GUI as we discussed. When it comes up there is already something there in the LAS Dir field - I delete that old data string and add in the directory for the survey I am trying to run through LiPROD.

![image](https://user-images.githubusercontent.com/44785008/93282938-7995ad80-f79d-11ea-8e80-b51c6a2c4d7e.png)

**Comment by forkozi** [comment]
Is everyone ok if we close this issue?  It sounds like the issue was due to moving the dataset after running LiPROD.

**Comment by gimahori** [comment]
Yes -I can close - I guess the moral of the story is if we move the data and rerun it - delete the old project tracking file.
