### ISSUE TITLE
LiProd-1.0.2 - alpha | Traceback Error | TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by jkspring** [noaa-rsd/LiProd#8]
Getting this traceback error when trying to cut NBS ellipsoid tiles.

Input: \\ngs-s-rsd\Geocue01\iocm_deliverables\lidar\PR1601-TB-N\CLASSIFIED_LAS\PR_CC_TPU
Output: \\ngs-s-rsd\Lidar_Proc01\2016\PR1401_BB_CC_880_p\08_RECEIVED\LiPROD_BLK_CC

_generating \\ngs-s-rsd\Lidar_Proc01\2016\PR1401_BB_CC_880_p\08_RECEIVED\LiPROD\NBS\ellipsoid\PR1401_BB_CC_880_p_US4PR1DJ_1m_total_tvu.tif...
clipping DEM to cell geometry...
generating coverage geometry feature...
Traceback (most recent call last):
  File "C:\LiProd-1.0.2-alpha\LiPROD.py", line 422, in <module>
    tracker.update_status(*d1_info)
  File "C:\LiProd-1.0.2-alpha\LiTracker.py", line 80, in update_status
    self.status['projects'][0]['cells'][self.get_cell_idx(cell)]['products'][product-1][event] = status
TypeError: list indices must be integers or slices, not NoneType_

![image](https://user-images.githubusercontent.com/35336539/84923017-aa7a1f80-b094-11ea-94ee-a0452d8f790d.png)

**Comment by forkozi** [comment]
sorry...can you help me remember...did we chat about this?

**Comment by forkozi** [comment]
no longer relevant...tracking system refactored to use csv, not json
