### ISSUE TITLE
error when 

### ISSUE THREAD

**Issue by gimahori** [noaa-rsd/LiProd#9]
Hi Nick,

I got this error again after loading anaconda on the rack server:

![image](https://user-images.githubusercontent.com/44785008/84937704-2fbbff00-b0aa-11ea-9233-616df4b1fadd.png)
 It looked like the default installation string was different so I used the one I have on my tower: C:\Users\gretchen.imahori\AppData\Local\Continuum\anaconda3 but it still is giving me the same error.  Thoughts?
thx,
g

**Comment by forkozi** [comment]
the solution was to delete the anaconda_dir.txt file, and then re-run LiPROD
